apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgres.db.movetokube.com
spec:
  group: db.movetokube.com
  names:
    kind: Postgres
    listKind: PostgresList
    plural: postgres
    singular: postgres
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Postgres is the Schema for the postgres API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: PostgresSpec defines the desired state of Postgres
            properties:
              database:
                type: string
              dropOnDelete:
                type: boolean
              extensions:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              masterRole:
                type: string
              schemas:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
            required:
            - database
            type: object
          status:
            description: PostgresStatus defines the observed state of Postgres
            properties:
              extensions:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              roles:
                description: PostgresRoles stores the different group roles for database
                properties:
                  owner:
                    type: string
                  reader:
                    type: string
                  writer:
                    type: string
                required:
                - owner
                - reader
                - writer
                type: object
              schemas:
                items:
                  type: string
                type: array
                x-kubernetes-list-type: set
              succeeded:
                type: boolean
            required:
            - roles
            - succeeded
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
