apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ext-postgres-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - events
    verbs:
      - "*"
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resourceNames:
      - ext-postgres-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - db.movetokube.com
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - "*"
