# permissions for end users to view postgres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: postgres-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-operator
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgres-viewer-role
rules:
- apiGroups:
  - db.movetokube.com
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - db.movetokube.com
  resources:
  - postgres/status
  verbs:
  - get
