apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  labels:
    app.kubernetes.io/name: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-db
spec:
  database: test-db # Name of database created in PostgreSQL
  dropOnDelete: false # Set to true if you want the operator to drop the database and role when this CR is deleted
  masterRole: test-db-group
  schemas: # List of schemas the operator should create in database
    - stores
    - customers
