package postgres

const (
	CREATE_DB       = `CREATE DATABASE "%s"`
	CREATE_ROLE     = `CREATE ROLE "%s" WITH LOGIN PASSWORD '%s'`
	UPDATE_PASSWORD = `ALTER ROLE "%s" WITH PASSWORD '%s'`
	DROP_ROLE       = `DROP ROLE "%s"`
	GRANT_PRIVS     = `GRANT ALL PRIVILEGES ON DATABASE "%s" TO "%s"`
	DROP_PRIVS      = `REVOKE ALL PRIVILEGES ON DATABASE "%s" FROM "%s"`
	REASIGN_OBJECTS = `REASSIGN OWNED BY "%s" TO "%s"`
)
